---
- name: start web-server
  hosts: all
  become: yes

  tasks:
  - name: download apache2
    apt: name=apache2 state=latest

  - name: start and enable apache2
    service: name=apache2 state=started enabled=yes
